# Generated by Django 4.0.4 on 2022-06-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_sold',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='preview',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.subject'),
        ),
    ]
